### ISSUE TITLE
fieldsCaseInsensitive has no effect

### ISSUE THREAD

**Issue by ewenw** [nodeGame/nodegame-mturk#7]
changing fieldsCaseInsensitive to true in the config does not read fields in all lowercase.

**Comment by shakty** [comment]
In fact, it was not implemented. I am working on it in branch fieldsInsentitive, will be ready in a few days, together with a few more features and updated doc

**Comment by shakty** [comment]
Should be fixed now. Please check the branch fieldsInsensitive and let me know.
